import pandas as pd
from datetime import datetime
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment

# ==========================
# CSV 읽기
# ==========================

df = pd.read_csv("Certificates.csv")

# ==========================
# 한국만
# ==========================

korea = df[df["Country"] == "KR"].copy()

# ==========================
# ISCC PLUS / EU만
# ==========================

korea = korea[
    korea["Certificate"].str.contains(
        "ISCC-PLUS|EU-ISCC",
        na=False
    )
].copy()

print(f"한국 인증서 : {len(korea)}")

# ==========================
# CB 이름 정리
# ==========================

def normalize_cb(cb):

    cb = str(cb)

    if "Control Union" in cb:
        return "Control Union"

    if "Korean Foundation for Quality" in cb:
        return "KFQ"

    if "KFQ" in cb:
        return "KFQ"

    if "Bureau Veritas" in cb:
        return "Bureau Veritas"

    if "SGS" in cb:
        return "SGS"

    if "FITI" in cb:
        return "FITI"

    if "DNV" in cb:
        return "DNV"

    if "BM Certification" in cb:
        return "BM Certification"

    return "Other"

korea["CB"] = korea["Issuing_CB"].apply(normalize_cb)
# ==========================
# Scheme 구분
# ==========================

def get_scheme(cert):

    cert = str(cert)

    if "ISCC-PLUS" in cert:
        return "ISCC PLUS"

    if "EU-ISCC" in cert:
        return "ISCC EU"

    return "Other"

korea["Scheme"] = korea["Certificate"].apply(get_scheme)

# ==========================
# Summary
# ==========================

summary = (
    korea
    .groupby(["CB", "Scheme"])
    .size()
    .unstack(fill_value=0)
)

# 혹시 컬럼이 없으면 생성
if "ISCC PLUS" not in summary.columns:
    summary["ISCC PLUS"] = 0

if "ISCC EU" not in summary.columns:
    summary["ISCC EU"] = 0

summary = summary[["ISCC PLUS", "ISCC EU"]]

summary["TOTAL"] = summary.sum(axis=1)

summary["Market Share (%)"] = (
    summary["TOTAL"] /
    summary["TOTAL"].sum() *
    100
).round(1)

print()
print("===== SUMMARY =====")
print(summary)
# ==========================
# Expiring (30일 이내)
# ==========================

korea["Valid_until"] = pd.to_datetime(
    korea["Valid_until"],
    errors="coerce"
)

today = pd.Timestamp.today()

expiring = korea.copy()

expiring["Days Left"] = (
    expiring["Valid_until"] - today
).dt.days

expiring = expiring[
    (expiring["Days Left"] >= 0)
    &
    (expiring["Days Left"] <= 30)
]
print()

print("===== Expiring =====")

print(
    expiring[
        [
            "Certificate_Holder",
            "CB",
            "Scheme",
            "Valid_until",
            "Days Left"
        ]
    ]
)
print("===================")
# ==========================
# Excel 저장
# ==========================

with pd.ExcelWriter(
    "ISCC_Korea_Report.xlsx",
    engine="openpyxl"
) as writer:

    # Sheet1
    summary.to_excel(
        writer,
        sheet_name="Summary"
    )

    # Sheet2
    expiring.to_excel(
        writer,
        sheet_name="Expiring_30Days",
        index=False
    )

print()
print("Excel 저장 완료!")
# ==========================
# HTML Summary 저장
# ==========================

report_date = datetime.now().strftime("%Y-%m-%d")

html_table = summary.to_html(
    border=0,
    justify="center",
    classes="summary-table"
)

html = f"""
<html>

<head>

<style>

body {{
    font-family: Arial, sans-serif;
    margin:40px;
}}

h2 {{
    color:#1F4E79;
}}

.summary-table {{
    border-collapse: collapse;
    width: 700px;
}}

.summary-table th {{
    background:#1F4E79;
    color:white;
    padding:8px;
    border:1px solid #ddd;
}}

.summary-table td {{
    padding:8px;
    text-align:center;
    border:1px solid #ddd;
}}

.summary-table tr:nth-child(even) {{
    background:#f5f5f5;
}}

</style>

</head>

<body>

<h2>📊 ISCC Korea Weekly Report</h2>

<p><b>Date :</b> {report_date}</p>

{html_table}

<br>

<p>
This report was automatically generated by the KFQ ISCC AutoReporter.
</p>

</body>

</html>
"""

with open("summary.html", "w", encoding="utf-8") as f:
    f.write(html)

with open(
    "summary.html",
    "w",
    encoding="utf-8"
) as f:

    f.write(f"""
    <html>

    <body>

    <h2>ISCC Korea Weekly Report</h2>

    {html_table}

    </body>

    </html>
    """)

print("HTML 저장 완료!")